const FLASHCARD_DATA = {
  "First Grade High Frequency Words List 1": [
    { "word": "the", "sentence": "Look at the big dog." },
    { "word": "of", "sentence": "She has a cup of milk." },
    { "word": "and", "sentence": "I like cats and dogs." },
    { "word": "a", "sentence": "He saw a red bird." },
    { "word": "to", "sentence": "We walk to the park." },
    { "word": "in", "sentence": "The toy is in the box." },
    { "word": "is", "sentence": "This is my favorite book." },
    { "word": "you", "sentence": "Do you want to play?" },
    { "word": "that", "sentence": "Look at that bright star." },
    { "word": "it", "sentence": "It is raining today." }
  ],
  "First Grade High Frequency Words List 2": [
    { "word": "he", "sentence": "He likes to ride his bike." },
    { "word": "for", "sentence": "This gift is for you." },
    { "word": "are", "sentence": "We are going to school." },
    { "word": "with", "sentence": "Come play with my new toy." },
    { "word": "they", "sentence": "They are eating some apples." },
    { "word": "was", "sentence": "The sun was warm today." },
    { "word": "on", "sentence": "The cat sat on the mat." },
    { "word": "as", "sentence": "Be as quick as a bunny." },
    { "word": "his", "sentence": "He lost his blue hat." },
    { "word": "I", "sentence": "I can read by myself." }
  ],
  "First Grade High Frequency Words List 3": [
    { "word": "at", "sentence": "Look at the little bug." },
    { "word": "this", "sentence": "This is a fun game." },
    { "word": "one", "sentence": "I have one sweet puppy." },
    { "word": "by", "sentence": "We stood by the big tree." },
    { "word": "but", "sentence": "I want to go out, but it is cold." },
    { "word": "be", "sentence": "I want to be a doctor." },
    { "word": "or", "sentence": "Do you want milk or water?" },
    { "word": "had", "sentence": "We had fun at the park." },
    { "word": "words", "sentence": "I can spell five words." },
    { "word": "not", "sentence": "That is not my backpack." }
  ],
  "First Grade High Frequency Words List 4": [
    { "word": "what", "sentence": "What is your favorite color?" },
    { "word": "were", "sentence": "They were playing outside." },
    { "word": "when", "sentence": "When will we go home?" },
    { "word": "can", "sentence": "You can do a great job." },
    { "word": "there", "sentence": "There is a bird in the tree." },
    { "word": "all", "sentence": "We ate all the snacks." },
    { "word": "we", "sentence": "We love to read together." },
    { "word": "your", "sentence": "Is this your yellow coat?" },
    { "word": "said", "sentence": "Mom said it is time for bed." },
    { "word": "use", "sentence": "I use a pencil to write." }
  ],
  "First Grade High Frequency Words List 5": [
    { "word": "an", "sentence": "I ate an orange for lunch." },
    { "word": "which", "sentence": "Which toy do you like best?" },
    { "word": "do", "sentence": "Do you know how to swim?" },
    { "word": "will", "sentence": "We will see a movie soon." },
    { "word": "other", "sentence": "The other shoe is under the bed." },
    { "word": "each", "sentence": "Each child got a balloon." },
    { "word": "she", "sentence": "She has pretty long hair." },
    { "word": "how", "sentence": "How do you make a paper airplane?" },
    { "word": "up", "sentence": "Look up at the blue sky." },
    { "word": "about", "sentence": "Tell me a story about a dragon." }
  ],
  "First Grade High Frequency Words List 6": [
    { "word": "out", "sentence": "Please take the trash out." },
    { "word": "then", "sentence": "We will eat lunch, then play outside." },
    { "word": "these", "sentence": "These blocks are fun to build with." },
    { "word": "some", "sentence": "Can I have some more water?" },
    { "word": "would", "sentence": "Would you like a cookie?" },
    { "word": "many", "sentence": "How many stars can you count?" },
    { "word": "them", "sentence": "I saw them running in the grass." },
    { "word": "so", "sentence": "The puppy is so soft and cute." },
    { "word": "her", "sentence": "I gave her a nice flower." },
    { "word": "make", "sentence": "Let's make a big sandcastle." }
  ],
  "First Grade High Frequency Words List 7": [
    { "word": "like", "sentence": "I like to eat sweet strawberries." },
    { "word": "into", "sentence": "The frog jumped into the pond." },
    { "word": "has", "sentence": "He has a cool red truck." },
    { "word": "two", "sentence": "I have two hands and two feet." },
    { "word": "write", "sentence": "I can write my own name." },
    { "word": "him", "sentence": "Give him the big green ball." },
    { "word": "time", "sentence": "It is time to go to bed." },
    { "word": "look", "sentence": "Look at the colorful butterfly!" },
    { "word": "more", "sentence": "Can I have one more story?" },
    { "word": "number", "sentence": "What is your lucky number?" }
  ],
  "First Grade High Frequency Words List 8": [
    { "word": "no", "sentence": "There is no more milk left." },
    { "word": "could", "sentence": "I wish I could fly like a bird." },
    { "word": "my", "sentence": "This is my favorite green shirt." },
    { "word": "first", "sentence": "He won first place in the race." },
    { "word": "been", "sentence": "I have been good all day." },
    { "word": "way", "sentence": "Show me the way to the playground." },
    { "word": "people", "sentence": "There are many people at the zoo." },
    { "word": "than", "sentence": "A horse is bigger than a dog." },
    { "word": "water", "sentence": "Drink water when you are thirsty." },
    { "word": "called", "sentence": "The little cat is called Fluffy." }
  ],
  "First Grade High Frequency Words List 9": [
    { "word": "who", "sentence": "Who is knocking at the door?" },
    { "word": "sit", "sentence": "Please sit on the blue rug." },
    { "word": "find", "sentence": "Can you find my lost sock?" },
    { "word": "down", "sentence": "The slide goes fast down to the ground." },
    { "word": "did", "sentence": "Did you see that big airplane?" },
    { "word": "oil", "sentence": "We use oil to cook the food." },
    { "word": "now", "sentence": "We need to leave for school now." },
    { "word": "long", "sentence": "The train has a very long track." },
    { "word": "day", "sentence": "Today is a beautiful sunny day." },
    { "word": "get", "sentence": "Go get your warm winter coat." }
  ],
  "First Grade High Frequency Words List 10": [
    { "word": "come", "sentence": "Come over and play at my house." },
    { "word": "have", "sentence": "I have three red markers." },
    { "word": "their", "sentence": "The birds built their nest here." },
    { "word": "go", "sentence": "Let's go to the candy shop." },
    { "word": "may", "sentence": "May I please have a turn?" },
    { "word": "made", "sentence": "We made a nice card for Grandma." },
    { "word": "from", "sentence": "This letter is from my cousin." },
    { "word": "if", "sentence": "If it rains, we will play inside." },
    { "word": "see", "sentence": "I see a tiny brown mouse." },
    { "word": "part", "sentence": "Which part of the game is your favorite?" }
  ],
  "First Grade High Frequency Words List 11": [
    { "word": "over", "sentence": "The cow jumped over the moon." },
    { "word": "sound", "sentence": "The loud bell makes a ringing sound." },
    { "word": "only", "sentence": "I have only one loose tooth left." },
    { "word": "work", "sentence": "Do your school work with care." },
    { "word": "place", "sentence": "This park is a great place to play." },
    { "word": "new", "sentence": "I got a shiny new bike." },
    { "word": "take", "sentence": "Take an umbrella so you stay dry." },
    { "word": "little", "sentence": "The little puppy barked softly." },
    { "word": "know", "sentence": "I know how to tie my shoes." },
    { "word": "years", "sentence": "I am six years old now." }
  ],
  "First Grade High Frequency Words List 12": [
    { "word": "live", "sentence": "Fish live under the deep blue water." },
    { "word": "back", "sentence": "Put the book back on the shelf." },
    { "word": "most", "sentence": "Most kids love to eat sweet ice cream." },
    { "word": "after", "sentence": "We will play after we finish lunch." },
    { "word": "our", "sentence": "Welcome to our cozy little home." },
    { "word": "me", "sentence": "Can you throw the ball to me?" },
    { "word": "give", "sentence": "Give your friend a high five." },
    { "word": "very", "sentence": "The giant cake was very yummy." },
    { "word": "things", "sentence": "Pack your things in your school bag." },
    { "word": "just", "sentence": "I just finished reading my first book." }
  ],
  "First Grade High Frequency Words List 13": [
    { "word": "name", "sentence": "My name is written right here." },
    { "word": "sentence", "sentence": "Write a short sentence about your pet." },
    { "word": "think", "sentence": "I think it is going to snow." },
    { "word": "great", "sentence": "You did a great job today!" },
    { "word": "help", "sentence": "Please help me clean up the toys." },
    { "word": "good", "sentence": "Have a good day at school!" },
    { "word": "man", "sentence": "The tall man waved hello to us." },
    { "word": "say", "sentence": "What did the teacher say to you?" },
    { "word": "where", "sentence": "Where did you put my yellow pencil?" },
    { "word": "through", "sentence": "The train went through the dark tunnel." }
  ],
  "First Grade High Frequency Words List 14": [
    { "word": "much", "sentence": "How much do you love candy?" },
    { "word": "line", "sentence": "Stand in a straight line at the door." },
    { "word": "too", "sentence": "The hot soup is too warm to eat." },
    { "word": "old", "sentence": "This old toy is still my favorite." },
    { "word": "same", "sentence": "We are wearing the same red shirt." },
    { "word": "before", "sentence": "Wash your sticky hands before you eat." },
	{ "word": "right", "sentence": "Turn right at the big tree." },
	{ "word": "means", "sentence": "A red light means you must stop." },
	{ "word": "any", "sentence": "Do you have any green crayons?" },
	{ "word": "tell", "sentence": "Tell me your favorite funny joke." }
  ],
  "First Grade High Frequency Words List 15": [
    { "word": "boy", "sentence": "The little boy ran down the hill." },
	{ "word": "came", "sentence": "A package came in the mail today." },
	{ "word": "show", "sentence": "Show me your cool drawing." },
	{ "word": "around", "sentence": "We ran around the playground." },
	{ "word": "three", "sentence": "The bird laid three small blue eggs." },
	{ "word": "following", "sentence": "The puppy is following me home." },
	{ "word": "want", "sentence": "I want a big slice of pizza." },
	{ "word": "also", "sentence": "I like apples and I also like grapes." },
	{ "word": "form", "sentence": "Ice will form when water gets very cold." },
	{ "word": "small", "sentence": "The small mouse ate a crumb of cheese." }
  ]
};